export const studentLoginDetail = {
	studentId: "ksorathiya761",
	password: "Ndu772bd",
	fullName: "Krish Anilbhai Sorathiya",
	studentReferenceNo: "ND2390761",
};

export const ALL_COUNTRIES = [
	{ label: "Aland Islands", value: "Aland Islands" },
	{ label: "Albania", value: "Albania" },
	{ label: "Algeria", value: "Algeria" },
	{ label: "American Samoa", value: "American Samoa" },
	{ label: "Andorra", value: "Andorra" },
	{ label: "Angola", value: "Angola" },
	{ label: "Anguilla", value: "Anguilla" },
	{ label: "Antigua and Barbuda", value: "Antigua and Barbuda" },
	{ label: "Argentina", value: "Argentina" },
	{ label: "Armenia", value: "Armenia" },
	{ label: "Aruba", value: "Aruba" },
	{ label: "Australia", value: "Australia" },
	{ label: "Austria", value: "Austria" },
	{ label: "Azerbaijan", value: "Azerbaijan" },
	{ label: "Bahamas", value: "Bahamas" },
	{ label: "Bahrain", value: "Bahrain" },
	{ label: "Bangladesh", value: "Bangladesh" },
	{ label: "Barbados", value: "Barbados" },
	{ label: "Belgium", value: "Belgium" },
	{ label: "Benin", value: "Benin" },
	{ label: "Bermuda", value: "Bermuda" },
	{ label: "Bolivia", value: "Bolivia" },
	{
		label: "Bonaire, Saint Eustatius and Saba",
		value: "Bonaire, Saint Eustatius and Saba",
	},
	{ label: "Botswana", value: "Botswana" },
	{ label: "Brazil", value: "Brazil" },
	{ label: "Brunei", value: "Brunei" },
	{ label: "Bulgaria", value: "Bulgaria" },
	{ label: "Burkina Faso", value: "Burkina Faso" },
	{ label: "Burundi", value: "Burundi" },
	{ label: "Cambodia", value: "Cambodia" },
	{ label: "Cameroon", value: "Cameroon" },
	{ label: "Canada", value: "Canada" },
	{ label: "Cape Verde", value: "Cape Verde" },
	{ label: "Cayman Islands", value: "Cayman Islands" },
	{ label: "Chad", value: "Chad" },
	{ label: "Chile", value: "Chile" },
	{ label: "China", value: "China" },
	{ label: "Christmas Island", value: "Christmas Island" },
	{ label: "Cocos (Keeling) Islands", value: "Cocos (Keeling) Islands" },
	{ label: "Colombia", value: "Colombia" },
	{ label: "Cook Islands", value: "Cook Islands" },
	{ label: "Costa Rica", value: "Costa Rica" },
	{ label: "Cote D'Ivoire", value: "Cote D'Ivoire" },
	{ label: "Croatia", value: "Croatia" },
	{ label: "Curaçao", value: "Curaçao" },
	{ label: "Cyprus", value: "Cyprus" },
	{ label: "Czech Republic", value: "Czech Republic" },
	{ label: "Denmark", value: "Denmark" },
	{ label: "Dominica", value: "Dominica" },
	{ label: "Dominican Republic", value: "Dominican Republic" },
	{ label: "East Timor", value: "East Timor" },
	{ label: "Ecuador", value: "Ecuador" },
	{ label: "Egypt", value: "Egypt" },
	{ label: "El Salvador", value: "El Salvador" },
	{ label: "Equatorial Guinea", value: "Equatorial Guinea" },
	{ label: "Estonia", value: "Estonia" },
	{ label: "Ethiopia", value: "Ethiopia" },
	{ label: "Faroe Islands", value: "Faroe Islands" },
	{ label: "Fiji Islands", value: "Fiji Islands" },
	{ label: "Finland", value: "Finland" },
	{ label: "France", value: "France" },
	{ label: "French Guiana", value: "French Guiana" },
	{ label: "French Polynesia", value: "French Polynesia" },
	{ label: "Gabon", value: "Gabon" },
	{ label: "Georgia", value: "Georgia" },
	{ label: "Germany", value: "Germany" },
	{ label: "Ghana", value: "Ghana" },
	{ label: "Gibraltar", value: "Gibraltar" },
	{ label: "Greece", value: "Greece" },
	{ label: "Greenland", value: "Greenland" },
	{ label: "Grenada", value: "Grenada" },
	{ label: "Guadeloupe", value: "Guadeloupe" },
	{ label: "Guam", value: "Guam" },
	{ label: "Guatemala", value: "Guatemala" },
	{ label: "Guernsey", value: "Guernsey" },
	{ label: "Honduras", value: "Honduras" },
	{ label: "Hong Kong S.A.R.", value: "Hong Kong S.A.R." },
	{ label: "Hungary", value: "Hungary" },
	{ label: "Iceland", value: "Iceland" },
	{ label: "India", value: "India" },
	{ label: "Indonesia", value: "Indonesia" },
	{ label: "Ireland", value: "Ireland" },
	{ label: "Isle of Man", value: "Isle of Man" },
	{ label: "Israel", value: "Israel" },
	{ label: "Italy", value: "Italy" },
	{ label: "Jamaica", value: "Jamaica" },
	{ label: "Japan", value: "Japan" },
	{ label: "Jersey", value: "Jersey" },
	{ label: "Jordan", value: "Jordan" },
	{ label: "Kazakhstan", value: "Kazakhstan" },
	{ label: "Kenya", value: "Kenya" },
	{ label: "Kiribati", value: "Kiribati" },
	{ label: "Kosovo", value: "Kosovo" },
	{ label: "Kuwait", value: "Kuwait" },
	{ label: "Kyrgyzstan", value: "Kyrgyzstan" },
	{ label: "Laos", value: "Laos" },
	{ label: "Latvia", value: "Latvia" },
	{ label: "Liechtenstein", value: "Liechtenstein" },
	{ label: "Lithuania", value: "Lithuania" },
	{ label: "Luxembourg", value: "Luxembourg" },
	{ label: "Macau S.A.R.", value: "Macau S.A.R." },
	{ label: "Macedonia", value: "Macedonia" },
	{ label: "Malawi", value: "Malawi" },
	{ label: "Malaysia", value: "Malaysia" },
	{ label: "Maldives", value: "Maldives" },
	{ label: "Mali", value: "Mali" },
	{ label: "Malta", value: "Malta" },
	{ label: "Marshall Islands", value: "Marshall Islands" },
	{ label: "Martinique", value: "Martinique" },
	{ label: "Mauritius", value: "Mauritius" },
	{ label: "Mayotte", value: "Mayotte" },
	{ label: "Mexico", value: "Mexico" },
	{ label: "Micronesia", value: "Micronesia" },
	{ label: "Moldova", value: "Moldova" },
	{ label: "Monaco", value: "Monaco" },
	{ label: "Mongolia", value: "Mongolia" },
	{ label: "Montserrat", value: "Montserrat" },
	{ label: "Morocco", value: "Morocco" },
	{ label: "Mozambique", value: "Mozambique" },
	{ label: "Nauru", value: "Nauru" },
	{ label: "Nepal", value: "Nepal" },
	{ label: "Netherlands Antilles", value: "Netherlands Antilles" },
	{ label: "Netherlands (Holland)", value: "Netherlands (Holland)" },
	{ label: "New Caledonia", value: "New Caledonia" },
	{ label: "New Zealand", value: "New Zealand" },
	{ label: "Nicaragua", value: "Nicaragua" },
	{ label: "Niger", value: "Niger" },
	{ label: "Nigeria", value: "Nigeria" },
	{ label: "Niue", value: "Niue" },
	{ label: "Norfolk Island", value: "Norfolk Island" },
	{ label: "Northern Mariana Islands", value: "Northern Mariana Islands" },
	{ label: "Norway", value: "Norway" },
	{ label: "Oman", value: "Oman" },
	{ label: "Pakistan", value: "Pakistan" },
	{ label: "Palau", value: "Palau" },
	{ label: "Panama", value: "Panama" },
	{ label: "Paraguay", value: "Paraguay" },
	{ label: "Peru", value: "Peru" },
	{ label: "Philippines", value: "Philippines" },
	{ label: "Pitcairn Island", value: "Pitcairn Island" },
	{ label: "Poland", value: "Poland" },
	{ label: "Portugal", value: "Portugal" },
	{ label: "Puerto Rico", value: "Puerto Rico" },
	{ label: "Qatar", value: "Qatar" },
	{ label: "Reunion", value: "Reunion" },
	{ label: "Romania", value: "Romania" },
	{ label: "Rwanda", value: "Rwanda" },
	{ label: "Saint Barthelemy", value: "Saint Barthelemy" },
	{ label: "Saint Kitts And Nevis", value: "Saint Kitts And Nevis" },
	{ label: "Saint Lucia", value: "Saint Lucia" },
	{ label: "Saint Martin", value: "Saint Martin" },
	{ label: "Saint Pierre and Miquelon", value: "Saint Pierre and Miquelon" },
	{
		label: "Saint Vincent and The Grenadines",
		value: "Saint Vincent and The Grenadines",
	},
	{ label: "San Marino", value: "San Marino" },
	{ label: "Saudi Arabia", value: "Saudi Arabia" },
	{ label: "Senegal", value: "Senegal" },
	{ label: "Seychelles", value: "Seychelles" },
	{ label: "Sierra Leone", value: "Sierra Leone" },
	{ label: "Singapore", value: "Singapore" },
	{ label: "Sint Maarten (Dutch part)", value: "Sint Maarten (Dutch part)" },
	{ label: "Slovakia", value: "Slovakia" },
	{ label: "Slovenia", value: "Slovenia" },
	{ label: "South Africa", value: "South Africa" },
	{ label: "South Korea", value: "South Korea" },
	{ label: "Spain", value: "Spain" },
	{ label: "Sri Lanka", value: "Sri Lanka" },
	{ label: "Suriname", value: "Suriname" },
	{
		label: "Svalbard and Jan Mayen Islands",
		value: "Svalbard and Jan Mayen Islands",
	},
	{ label: "Sweden", value: "Sweden" },
	{ label: "Switzerland", value: "Switzerland" },
	{ label: "Taiwan", value: "Taiwan" },
	{ label: "Tajikistan", value: "Tajikistan" },
	{ label: "Tanzania", value: "Tanzania" },
	{ label: "Thailand", value: "Thailand" },
	{ label: "Togo", value: "Togo" },
	{ label: "Tokelau", value: "Tokelau" },
	{ label: "Trinidad And Tobago", value: "Trinidad And Tobago" },
	{ label: "Tunisia", value: "Tunisia" },
	{ label: "Turkey", value: "Turkey" },
	{ label: "Turkmenistan", value: "Turkmenistan" },
	{ label: "Turks And Caicos Islands", value: "Turks And Caicos Islands" },
	{ label: "Tuvalu", value: "Tuvalu" },
	{ label: "Uganda", value: "Uganda" },
	{ label: "United Arab Emirates", value: "United Arab Emirates" },
	{ label: "United Kingdom", value: "United Kingdom" },
	{ label: "United States Of America", value: "United States Of America" },
	{ label: "Uruguay", value: "Uruguay" },
	{ label: "Uzbekistan", value: "Uzbekistan" },
	{ label: "Vatican City State", value: "Vatican City State" },
	{ label: "Vietnam", value: "Vietnam" },
	{ label: "Virgin Islands (British)", value: "Virgin Islands (British)" },
	{ label: "Virgin Islands (US)", value: "Virgin Islands (US)" },
	{ label: "Wallis and Futuna Islands", value: "Wallis and Futuna Islands" },
	{ label: "Western Sahara", value: "Western Sahara" },
];
