import DetailsForm from "@/components/DetailsForm";
import Navbar from "@/components/Navbar";
import Head from "next/head";
import { Toaster } from "react-hot-toast";

export default function Home() {
	return (
		<>
			<Head>
				<title>MCMine University Fees Portal</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main className="bg-gray-900 w-100 pb-12 gap-10 flex flex-col px-8">
				<Navbar />
				<div className="px-2 md:px-10 flex flex-col gap-10">
					<div className="flex flex-col gap-3 items-start">
						<h1 className="text-4xl font-medium bg-gradient-to-r from-cyan-500 to-blue-500 text-transparent bg-clip-text">
							McMine University Payment Portal
						</h1>
						<h2 className="text-3xl font-bold bg-white text-transparent bg-clip-text">
							Pay by card
						</h2>
						<p className="text-gray-300 font-light text-sm lg:text-base">
							Paying through the University’s online facility is the preferred
							method of payment, as it provides a flexible and easy way for you
							to make payments towards your tuition fees.
						</p>
					</div>
					<DetailsForm />
				</div>
				<Toaster />
			</main>
		</>
	);
}
