import StudentDetails from "@/components/StudentDetails";
import { studentLoginDetail } from "@/constants";
import { getToken } from "@/constants/token";
import Head from "next/head";
import { useRouter } from "next/router";
import { useEffect } from "react";
import { Toaster } from "react-hot-toast";

export default function Home() {
	const router = useRouter();
	useEffect(() => {
		if (typeof window !== "undefined") {
			if (!localStorage.getItem("token")) {
				router.push("/login");
			}
		}
	}, []);
	return (
		<>
			<Head>
				<title>MCMine University Fees Portal</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main className="w-100 min-h-screen pb-12 gap-10 flex flex-col px-4">
				<div className="px-2 md:px-10 flex flex-col gap-10">
					<div className="flex flex-col gap-3 items-start">
						<h1 className="text-4xl font-bold bg-gradient-to-r from-[#03618B] to-[#03618C] text-transparent bg-clip-text">
							Welcome {studentLoginDetail?.fullName},
						</h1>
						{/* <h1 className="text-5xl font-bold bg-gradient-to-r from-[#03618B] to-[#03618C] text-transparent bg-clip-text">
							Nord University Payment Portal
						</h1> */}
						{/* <h2 className="text-3xl font-bold bg-[#667A85] text-transparent bg-clip-text">
							Pay by card
						</h2> */}
					</div>
					<StudentDetails />
				</div>
				<Toaster />
			</main>
		</>
	);
}
